# Generated by Django 4.0.3 on 2022-04-10 12:06

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import forum.core.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=forum.core.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='forum_profile', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
