# Generated by Django 4.0.3 on 2022-04-10 08:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reputation',
            options={'verbose_name': 'Reputation', 'verbose_name_plural': 'Reputations'},
        ),
        migrations.AlterUniqueTogether(
            name='reputation',
            unique_together={('from_user', 'post')},
        ),
        migrations.AlterModelTable(
            name='reputation',
            table='reputations',
        ),
    ]
