# Generated by Django 4.0.3 on 2022-04-09 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_category_forum_post_topic_post_topic_post_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'get_latest_by': 'date_joined', 'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
    ]
