SIGNATURE_MAX_LENGTH = 1024

AVATARS_UPLOAD_TO = 'devproject/avatars'

AVATAR_WIDTH = 60

AVATAR_HEIGHT = 60

DEFAULT_MARKUP = 'bbcode'

FORUM_LOGO_UPLOAD_TO = 'forum/forum_logo'

FORUM_LOGO_WIDTH = 16

FORUM_LOGO_HEIGHT = 16
